# =========================
# Basic Site Settings
# =========================
title: "Parijat Maitra"
title_separator: "-"
name: "Parijat Maitra"
description: "PhD student in Economics at Stockholm University, working at the intersection of Labour and Development Economics."
url: "https://parijatmaitra.github.io"
baseurl: ""
repository: "ParijatMaitra/ParijatMaitra.github.io"

# =========================
# Theme (Minimal Mistakes)
# =========================
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"   # (change to "dark" later if you want)

# =========================
# Plugins
# =========================
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# =========================
# Author Profile (left sidebar)
# =========================
author:
  avatar    : "me.jpg"   # put your photo at: images/me.jpg
  name      : "Parijat Maitra"
  bio       : "PhD student in Economics"
  location  : "Stockholm, Sweden"
  email     : "parijat.maitra@su.se"
  googlescholar: "https://scholar.google.com/citations?user=0giGbfcAAAAJ&hl"
  orcid     : "https://orcid.org/0009-0003-9301-1576"
  github    : "ParijatMaitra"

# =========================
# Output & Permalinks
# =========================
permalink: /:categories/:title/
timezone: "Europe/Stockholm"

# =========================
# Collections (AcademicPages-style)
# =========================
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# =========================
# Defaults (page layouts)
# =========================
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      comments: false
      share: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true

# =========================
# Markdown & Sass
# =========================
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
sass:
  sass_dir: _sass
  style: compressed

# =========================
# Analytics (disabled)
# =========================
analytics:
  provider: "false"
