# =========================
# Basic Site Settings
# =========================
title: "Parijat Maitra"
title_separator: "-"
name: "Parijat Maitra"
description: "PhD student in Economics at Stockholm University, working at the intersection of Labour and Development Economics."
url: "https://parijatmaitra.github.io"   # Your site URL
baseurl: ""                              # Leave empty for a user site
repository: "ParijatMaitra/ParijatMaitra.github.io"

# =========================
# Theme Settings
# =========================
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"

# =========================
# Plugins
# =========================
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# =========================
# Author Profile
# =========================
author:
  avatar    : "me.jpg"   # put your image in /images/me.jpg
  name      : "Parijat Maitra"
  bio       : "PhD student in Economics"
  location  : "Stockholm, Sweden"
  email     : "parijat.maitra@su.se"
  orcid     : "https://orcid.org/0009-0003-9301-1576"
  googlescholar: "https://scholar.google.com/citations?user=0giGbfcAAAAJ&hl"
  github    : "ParijatMaitra"
  linkedin  : ""         # add if you have one
  twitter   : ""         # add if you want to show Twitter/X

# =========================
# Navigation
# =========================
# Edit the menu links shown at the top of your site
navigation:
  - title: "Research"
    url: /research/
  - title: "Teaching"
    url: /teaching/
  - title: "Publications"
    url: /publications/
  - title: "CV"
    url: /files/Parijat_Maitra_CV.pdf

# =========================
# Analytics (Google GA4)
# =========================
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-JYQZ0TK21L"
    anonymize_ip: true

# =========================
# Output & Permalinks
# =========================
permalink: /:categories/:title/
timezone: "Europe/Stockholm"

# =========================
# Collections
# =========================
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# =========================
# Defaults (page layouts)
# =========================
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      comments: false
      share: true
      related: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true

# =========================
# Markdown & Sass Settings
# =========================
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
sass:
  sass_dir: _sass
  style: compressed
