# Basic Settings
title: "Parijat Maitra"
name: "Parijat Maitra"
description: "PhD student in Economics at Stockholm University, working at the intersection of Labour and Development Economics."
url: "https://parijatmaitra.github.io"
baseurl: ""
repository: "ParijatMaitra/ParijatMaitra.github.io"

# Theme
theme: jekyll-theme-minimal-mistakes
remote_theme: nil
minimal_mistakes_skin: "default"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Author Profile
author:
  avatar : "me.jpg"
  name   : "Parijat Maitra"
  bio    : "PhD student in Economics"
  location : "Stockholm"
  email  : "parijat.maitra@su.se"
  github : "ParijatMaitra"
  googlescholar: "https://scholar.google.com/citations?user=0giGbfcAAAAJ&hl"
  orcid: "https://orcid.org/0009-0003-9301-1576"

# Navigation (menu top right)
navigation:
  - title: "Research"
    url: /research/

# Collections
collections:
  teaching:
    output: true
  publications:
    output: true
  portfolio:
    output: true
  talks:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Permalinks
permalink: /:categories/:title/
